# File Data Source Configuration
# For reading financial transaction CSV files with watching capabilities

datasource:
  type: "file"
  name: "financial_transactions_csv"
  config:
    # Primary data file path (supports glob patterns)
    path: "./demo_data/financial_transactions.csv"
    
    # File format configuration
    format: "csv"
    
    # CSV-specific options
    csv_options:
      has_headers: true
      delimiter: ","
      quote_char: "\""
      escape_char: "\\"
      
    # File watching configuration
    watching:
      enabled: true
      poll_interval_ms: 1000  # Check every second for changes
      
    # Buffer configuration for performance
    buffer.size: 8192  # 8KB read buffer
    
    # Schema inference settings
    schema:
      auto_detect: true
      sample_rows: 100
      
    # Error handling
    error_handling:
      skip_invalid_rows: true
      max_errors: 10
      log_errors: true
      
    # Performance tuning
    performance:
      read_ahead: true
      batch.size: 100
      
# Serialization format for downstream processing      
serialization:
  format: "avro"
  schema_file: "./schemas/financial_transaction.avsc"
  
# Processing hints
processing:
  # Decimal precision handling
  decimal_fields:
    - field: "amount"
      precision: 19
      scale: 4
      
  # Type conversions
  field_mappings:
    timestamp:
      type: "timestamp"
      format: "unix_seconds"
    amount:
      type: "scaled_decimal"
      scale: 4