# Kafka source configuration for raw transactions stream
# Flat structure with dot-notation properties

# Source type (required) 
type: "kafka_source"

# Kafka connection properties
bootstrap.servers: "localhost:9092"
topic: "raw-transactions"
group.id: "enhanced-demo-raw"

# Consumer settings
auto.offset.reset: "earliest"
enable.auto.commit: false
max.poll.records: 1000
fetch.min.bytes: 1024
fetch.max.wait.ms: 500

# Serialization
value.format: "json"
key.format: "string"

# Processing settings
batch.size: 1000
timeout_ms: 30000
max_retries: 3