# Common Kafka Data Source Configuration for Examples
# Base configuration for all Kafka data sources
# URIs are constructed as: kafka://{bootstrap_servers}/{topic_name}

datasource:
  type: kafka
  
  # Standard consumer configuration
  consumer_config:
    bootstrap.servers: "localhost:9092"
    auto.offset.reset: "latest"
    enable.auto.commit: true
    auto.commit.interval.ms: 100
    session.timeout.ms: 6000
    heartbeat.interval.ms: 2000
    
  # Common schema settings
  schema:
    key.format: string
    value.format: json
    
    # Schema Registry settings (for Avro/Protobuf)
    registry_url: "http://localhost:8081"
    # registry_username: "schema_user"
    # registry_password: "schema_pass"
    
    # Schema configuration examples (choose based on value.format)
    # For Avro format:
    # avro.schema: |
    #   {
    #     "type": "record",
    #     "name": "CommonRecord", 
    #     "fields": [
    #       {"name": "id", "type": "string"},
    #       {"name": "timestamp", "type": "long"},
    #       {"name": "payload", "type": "string"}
    #     ]
    #   }
    #
    # For Protobuf format:  
    # protobuf.schema: |
    #   syntax = "proto3";
    #   message CommonRecord {
    #     string id = 1;
    #     int64 timestamp = 2;
    #     string payload = 3;
    #   }
    #
    # Schema file alternatives:
    # avro.schema.file: "./schemas/common_record.avsc"  
    # protobuf.schema.file: "./schemas/common_record.proto"
    
  # Default performance settings
  performance:
    compression.type: "gzip"
    
  # Default stream properties
  stream.config:
    replication.factor: 1  # Single node for examples
    cleanup.policy: "delete"
    
# Performance profiles that can be referenced
performance_profiles:
  low_latency:
    fetch.max.wait.ms: 10
    max.poll.records: 500
    buffer.size: 32768
    
  high_throughput:
    fetch.max.wait.ms: 100
    max.poll.records: 2000
    buffer.size: 131072
    
  balanced:
    fetch.max.wait.ms: 50
    max.poll.records: 1000
    buffer.size: 65536