# Critical Alerts Output Configuration
# High-priority IoT alerts requiring immediate attention

extends: common_kafka_sink.yaml

topic:
  name: "critical_alerts"
  
delivery_profile: critical

topic_config:
  partitions: 8
  replication.factor: 3
  retention.ms: 2592000000  # 30 days retention for compliance
  
metadata:
  description: "Critical IoT sensor alerts"
  data.classification: "operational_critical"
  priority: "critical"