# Device Status Topic Configuration
# IoT device health and status monitoring

extends: common_kafka_source.yaml

topic:
  name: "device_status"
  
consumer.group: "iot_monitoring_group"
performance_profile: balanced

datasource:
  schema:
    key.field: device_id
    
topic_config:
  partitions: 6
  retention.ms: 2592000000  # 30 days retention
  
metadata:
  description: "IoT device status and health data"
  data.classification: "device_telemetry"
  update.frequency: "periodic"