# Orders Topic Configuration
# E-commerce orders data source

extends: common_kafka_source.yaml

topic:
  name: "orders"
  
consumer.group: "ecommerce_analytics_group"
performance_profile: balanced

datasource:
  schema:
    key.field: customer_id

topic_config:
  partitions: 4
  retention.ms: 604800000  # 7 days retention
  
metadata:
  description: "E-commerce orders stream"
  data.classification: "business_critical"
  update.frequency: "real_time"