# Pressure Alerts Output Configuration
# Pressure monitoring alerts

extends: common_kafka_sink.yaml

topic:
  name: "pressure_alerts"
  
delivery_profile: critical

topic_config:
  partitions: 6
  replication.factor: 2
  retention.ms: 2592000000  # 30 days retention
  
metadata:
  description: "Pressure monitoring alerts"
  data.classification: "safety_critical"
  priority: "critical"