# Product Analytics Output Configuration
# Product performance metrics

extends: common_kafka_sink.yaml

topic:
  name: "product_analytics_stream"
  
delivery_profile: medium_priority

topic_config:
  partitions: 4
  retention.ms: 2592000000  # 30 days retention
  
metadata:
  description: "Product performance analytics"
  data.classification: "analytical_data"
  priority: "medium"