# Sensor Health Reports Output Configuration
# Sensor health monitoring reports

extends: common_kafka_sink.yaml

topic:
  name: "sensor_health_reports"
  
delivery_profile: medium_priority

topic_config:
  partitions: 4
  retention.ms: 7776000000  # 90 days retention for health trending
  
metadata:
  description: "Sensor health monitoring reports"
  data.classification: "operational_data"
  priority: "medium"