# Social Posts Topic Configuration
# Real-time social media posts stream

extends: common_kafka_source.yaml

topic:
  name: "social_posts"
  
consumer.group: "social_analytics_group"
performance_profile: high_throughput

datasource:
  schema:
    key.field: post_id
    
topic_config:
  partitions: 16
  retention.ms: 604800000  # 7 days retention
  
metadata:
  description: "Social media posts stream"
  data.classification: "public_content"
  update.frequency: "real_time"