# Viral Content Alerts Output Configuration
# High engagement content detection

extends: common_kafka_sink.yaml

topic:
  name: "viral_content_alerts"
  
delivery_profile: high_priority

topic_config:
  partitions: 6
  retention.ms: 604800000  # 7 days retention
  
metadata:
  description: "Viral content detection alerts"
  data.classification: "content_analytics"
  priority: "high"