# Common Kafka Data Sink Configuration
# Base configuration for all Kafka data sinks in the trading system
# URIs are constructed as: kafka://{bootstrap_servers}/{topic_name}

datasink:
  type: kafka
  
  # Standard producer configuration
  producer_config:
    bootstrap.servers: "localhost:9092"
    retries: 3
    batch.size: 16384
    buffer_memory: 33554432
    max_in_flight_requests_per_connection: 5
    
  # Common schema settings
  schema:
    key.format: string
    value.format: avro
    # Note: Schema registry NOT used - Avro schemas are embedded in messages or loaded from files
    # schema.registry.url: "http://schema-registry:8081"
    
  # Default topic properties
  topic_config:
    replication.factor: 3
    cleanup.policy: "delete"
    segment_ms: 3600000  # 1 hour segments
    
  # Default headers for all messages
  headers:
    source_system: "velo_stream"
    compliance: "FR-047"
    
# Delivery profiles for different alert types
delivery_profiles:
  critical:
    acks: "all"
    linger.ms: 0
    compression.type: "lz4"
    max_in_flight_requests_per_connection: 1
    delivery_guarantee: "exactly_once"
    timeout_ms: 3000
    
  high_priority:
    acks: "1"
    linger.ms: 1
    compression.type: "lz4"
    delivery_guarantee: "at_least_once"
    timeout_ms: 5000
    
  medium_priority:
    acks: "1"
    linger.ms: 5
    compression.type: "snappy"
    delivery_guarantee: "at_least_once"
    timeout_ms: 8000
    
  balanced:
    acks: "1"
    linger.ms: 10
    compression.type: "gzip"
    delivery_guarantee: "at_least_once"
    timeout_ms: 10000