# Market Data File Source Configuration
# Configuration for reading market data from CSV file

data_source:
  type: file
  path: "./demo/trading/data/market_data.csv"
  format: csv
  has_headers: true

schema:
  fields:
    - name: symbol
      type: string
      nullable: false
    - name: exchange
      type: string
      nullable: false
    - name: price
      type: decimal
      precision: 10
      scale: 4
    - name: bid_price
      type: decimal
      precision: 10
      scale: 4
    - name: ask_price
      type: decimal
      precision: 10
      scale: 4
    - name: bid_size
      type: integer
    - name: ask_size
      type: integer
    - name: volume
      type: integer
    - name: timestamp
      type: timestamp
      format: "yyyy-MM-dd HH:mm:ss"

processing:
  mode: batch
  batch_size: 10000
  refresh_interval: "5 minutes"

output:
  retention: "1 day"
  format: avro
  compression: snappy