# Market Data Clean Sink - Cleaned 1-second tick buckets
# Output from tick aggregation with OHLC data

datasink:
  type: kafka

  producer_config:
    bootstrap.servers: "broker:9092"
    retries: 3
    acks: "all"
    linger.ms: 0
    compression.type: "lz4"
    batch.size: 16384

  schema:
    key.format: string
    value.format: avro
    schema.registry.url: "http://schema-registry:8081"

  topic:
    name: "market-data-clean"
    partitions: 12
    replication.factor: 3

  headers:
    source_system: "velostream"
    data_quality: "clean"
