# Order Imbalance Alerts Topic Configuration
# Order flow imbalance alerts output

extends: common_kafka_sink.yaml

# Topic-specific settings
topic:
  name: "order_imbalance_alerts"
  
# Medium priority delivery
delivery_profile: medium_priority

# Topic-specific schema
schema:
  key.field: symbol
  schema_file: "schemas/order_imbalance_alerts.avsc"
  
# Topic properties
topic_config:
  partitions: 4
  retention.ms: 172800000  # 2 days retention
  
# Alert-specific headers
headers:
  alert_type: "order_flow_imbalance"
  priority: "medium"
  analysis_type: "institutional_flow"
  
# Business context
metadata:
  description: "Order flow imbalance detection for institutional trading patterns"
  imbalance_threshold: "0.7"
  min_volume: 10000
  business_impact: "institutional_activity_detection"