# Order Imbalance Sink - Order flow imbalance alerts
# Detects institutional trading patterns from order book data

datasink:
  type: kafka

  producer_config:
    bootstrap.servers: "broker:9092"
    retries: 3
    acks: "1"
    linger.ms: 1
    compression.type: "lz4"
    batch.size: 16384

  schema:
    key.format: string
    value.format: avro
    value.serializer: "avro"
    value.schema.file: "schemas/order_imbalance_alerts.avsc"
    # Note: Schema registry NOT used - Avro schemas are embedded in messages or loaded from files
    # schema.registry.url: "http://schema-registry:8081"

  topic:
    name: "order-imbalance"
    partitions: 6
    replication.factor: 3

  headers:
    source_system: "velostream"
    alert_type: "order_imbalance"
    priority: "high"
