# Price Alerts Topic Configuration
# High-priority price movement alerts output

extends: common_kafka_sink.yaml

# Topic-specific settings
topic:
  name: "price_alerts"
  
# Delivery profile for high-priority alerts
delivery_profile: high_priority

# Topic-specific schema
schema:
  key.field: symbol
  value.schema.file: "schemas/price_alerts.avsc"
  
# Topic properties
topic_config:
  partitions: 6
  retention.ms: 604800000  # 7 days retention for alerts
  
# Alert-specific headers
headers:
  alert_type: "price_movement"
  priority: "high"
  
# Business context
metadata:
  description: "Real-time price movement alerts (>5% changes)"
  alert_threshold: "5_percent_price_change"
  business_impact: "trading_opportunity"