name: 'Setup Protocol Buffers Compiler'
description: 'Install protobuf compiler across Linux, macOS, and Windows platforms'

runs:
  using: 'composite'
  steps:
    - name: Install protobuf on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev
        protoc --version
      shell: bash

    - name: Install protobuf on macOS
      if: runner.os == 'macOS'
      run: |
        brew install protobuf
        protoc --version
      shell: bash

    - name: Install protobuf on Windows
      if: runner.os == 'Windows'
      run: |
        # Download pre-built protoc binary from GitHub releases
        $PROTOC_VERSION = "28.3"
        $PROTOC_ZIP = "protoc-${PROTOC_VERSION}-win64.zip"
        $PROTOC_URL = "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}"

        Write-Host "Downloading protoc ${PROTOC_VERSION}..."
        Invoke-WebRequest -Uri $PROTOC_URL -OutFile $PROTOC_ZIP

        Write-Host "Extracting protoc..."
        Expand-Archive -Path $PROTOC_ZIP -DestinationPath $env:TEMP\protoc -Force

        # Add to PATH for current session
        $PROTOC_BIN = "$env:TEMP\protoc\bin"
        echo "$PROTOC_BIN" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Verify installation
        & "$PROTOC_BIN\protoc.exe" --version

        Write-Host "Protobuf compiler installed successfully"
      shell: pwsh

    - name: Verify protobuf installation (Unix)
      if: runner.os != 'Windows'
      run: protoc --version
      shell: bash

    - name: Verify protobuf installation (Windows)
      if: runner.os == 'Windows'
      run: protoc --version
      shell: pwsh
